version: "2"

services:
  sonarqube:
    image: sonarqube:7.8-community
    ports:
      - "80:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - ./conf/sonar.properties:/opt/sonarqube/conf/sonar.properties
      - ./logs:/opt/sonarqube/logs
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    volumes_from:
      - plugins
    depends_on:
      - db
  db:
    image: postgres:10.9-alpine
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  plugins:
    image: mwizner/sonarqube-scala-plugins:3.7.0
    volumes:
      - sonarqube_plugins:/opt/sonarqube/extensions/plugins
    command: /bin/true

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_bundled-plugins:
  sonarqube_plugins:
  postgresql:
  postgresql_data:
